services:
  - type: web
    name: cv-hani-derrouiche
    env: python
    region: frankfurt  # "France" n’est pas une région Render valide
    plan: free
    branch: main
    buildCommand: |
      apt-get update && apt-get install -y wkhtmltopdf xfonts-75dpi xfonts-base libfontconfig
      pip install -r requirements.txt
    startCommand: gunicorn CV.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0  # dernière stable, pas 3.14 encore
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "True"
      - key: ALLOWED_HOSTS
        sync: false